# Generated by Django 4.2.4 on 2023-09-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.country'),
        ),
    ]
