# Generated by Django 4.2.4 on 2023-09-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_destination_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airoport',
            name='country',
        ),
        migrations.RemoveField(
            model_name='airoport',
            name='time_zone',
        ),
        migrations.DeleteModel(
            name='Airplane',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='airoport',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.RemoveField(
            model_name='route',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='route',
            name='origen',
        ),
        migrations.DeleteModel(
            name='Airoport',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='TimeZone',
        ),
    ]
