# Generated by Django 4.2.4 on 2023-09-06 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('company', models.CharField(max_length=30)),
                ('passengerCapaCity', models.PositiveIntegerField()),
                ('fuelCapacity', models.IntegerField()),
                ('kmInDrive', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='000', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmTotals', models.FloatField()),
                ('price', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_Route', to='airoport.city')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen_Routss', to='airoport.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airoport.country', to_field='name'),
        ),
        migrations.AddField(
            model_name='city',
            name='time_zone',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='airoport.timezone', to_field='name'),
        ),
        migrations.CreateModel(
            name='Airoport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('iata_code', models.CharField(default='Unknow', max_length=3, unique=True)),
                ('clasification', models.CharField(choices=[('Internacional', 'Internacional'), ('Nacional', 'Nacional')], default='Nacional', max_length=50)),
                ('Airlain', models.ManyToManyField(related_name='Airoport', to='airoport.airlain')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airoport.city', to_field='name')),
            ],
        ),
        migrations.AddField(
            model_name='airlain',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airoport.country', to_field='name'),
        ),
    ]
