# Generated by Django 4.2.4 on 2023-09-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airoport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airoport',
            name='Airlain',
        ),
        migrations.AddField(
            model_name='airlain',
            name='airoport',
            field=models.ManyToManyField(related_name='Airoport', to='airoport.airoport'),
        ),
    ]
